### ISSUE TITLE
Serial stops working in example sketch

### ISSUE THREAD

**Issue by barafael** [Pharap/FixedPointsArduino#17] opened 2018-03-06 08:56 UTC
When I run the example sketch on an arduino uno, the serial monitor stops printing in testQ7x8 at 'Displayin'(sic) just before showing the float result of a*b. Although when I move the multiplication test higher up, it works fine, but breaks later anyway. I have tried using different terminals to display serial (platformio device monitor on different emulators) as well as the arduino ide integrated serial monitor. It always breaks at some point. Just calling one of the two test functions also breaks, it just stops printing at some point. Just printing a string from a loop works fine, though.

It may well be that I made a stupid mistake somewhere, but just in case I wanted to ask here.

**Comment by Pharap** [comment] 2018-03-09 06:10
So that's [`TestSQ7x8`, line 151](https://github.com/Pharap/FixedPointsArduino/blob/master/examples/FixedPointCalculations/FixedPointCalculations.ino#L151) it stops at?

Were you using the test unedited when it first broke?

I happen to have an Arduino Uno so I thought I'd give it a test.
I deleted my copy of FixedPoints, obtained a new copy of the latest version, uploaded a fresh copy via the Arduino IDE v1.8.5 and gave it a run and it ran without any problems.
(On Windows 8.1)

It gave me an upload message of:

> Sketch uses 6150 bytes (19%) of program storage space. Maximum is 32256 bytes.
> Global variables use 200 bytes (9%) of dynamic memory, leaving 1848 bytes for local variables. Maximum is 2048 bytes.

And a serial monitor output of:

> The size of UQ8x8 on your system is:
> 2
> 
> Displaying a as float:
> 1.50
> 
> Displaying the integer part of a
> 1
> 
> Displaying floorFixed(a):
> 1.00
> 
> Displaying ceilFixed(a):
> 2.00
> 
> Displaying roundFixed(a):
> 2.00
> 
> Displaying truncFixed(a):
> 1.00
> 
> Displaying b as float:
> 5.25
> 
> Displaying the integer part of b
> 5
> 
> Displaying floorFixed(b):
> 5.00
> 
> Displaying ceilFixed(b):
> 6.00
> 
> Displaying roundFixed(b):
> 5.00
> 
> Displaying truncFixed(b):
> 5.00
> 
> Displaying a + b as float:
> 6.75
> 
> Displaying a - b as float:
> (Note the underflow due lack of sign bit)
> 252.25
> 
> Displaying b - a as float:
> 3.75
> 
> Displaying a * b as float:
> 7.88
> 
> Displaying a / b as float:
> 0.29
> 
> The size of SQ7x8 on your system is:
> 2
> 
> Displaying a as float:
> 1.50
> 
> Displaying the integer part of a
> 1
> 
> Displaying floorFixed(a):
> 1.00
> 
> Displaying ceilFixed(a):
> 2.00
> 
> Displaying roundFixed(a):
> 2.00
> 
> Displaying truncFixed(a):
> 1.00
> 
> Displaying b as float:
> 5.25
> 
> Displaying the integer part of b
> 5
> 
> Displaying floorFixed(b):
> 5.00
> 
> Displaying ceilFixed(b):
> 6.00
> 
> Displaying roundFixed(b):
> 5.00
> 
> Displaying truncFixed(b):
> 5.00
> 
> Displaying a + b as float:
> 6.75
> 
> Displaying a - b as float:
> (Note this is correct due to sign bit)
> -3.75
> 
> Displaying b - a as float:
> 3.75
> 
> Displaying a * b as float:
> 7.88
> 
> Displaying a / b as float:
> 0.29
> 

---

Have you tried using a different USB cable in case the cable isn't working properly?
Is it stopping in the same place repeatably?
(i.e. if you reset the board does it always stop in the same place?)
And is this the only thing that's causing a serial issue?
Have you tested other serial heavy programs?

**Comment by barafael** [comment] 2018-03-09 07:31
Yes, it stops repeatedly at the same place. I have tried a different Uno and a different computer with equal results, but not a different cable. If I just print text from a forever running while loop, it works as intended, but I have not tried printing long lines yet.

It always stops at the same point when I run the unmodified sketch, but when I comment out either call to a test function, it stops in sort of random places.

It definitely sounds like some issue on my part, I will post if I find any other clues.

Thanks for getting back to me!

**Comment by Pharap** [comment] 2018-03-09 08:17
I won't close the issue yet just in case it's not an issue on your end,
but it seems more likely at the moment.

Usually if text stops mid-sentence it's because the serial connection has been interrupted somehow (cable removed, device turned off etc).
Since printing happens synchronously and it stops in the middle of a text block rather than when it reaches a function call that suggests to me that the issue lies in either the serial printing function or the serial communication itself.

Do you have any other Arduino boards you could try it on? (i.e. non-Uno boards)

Also, no problem, I'm just happy to hear that my library is being put to use.

**Comment by barafael** [comment] 2018-03-10 17:33
I have tried an arduino mega 2560 with another cable, as well as another computer. Both computers run arch, though.
The issue persists - output always stops after printing "Displayin". Note that the connection does not break! If I unplug the cable or make the uC crash, there is a SerialException in the monitor program (pyserial). This does not happen when I try to print the fixed-point results.
I think I should try using a different OS.

**Comment by Pharap** [comment] 2018-03-10 18:21
It's possible it's OS-related, e.g. a bug in the driver.

I've run the same code on both Uno and Leonardo and I've had people confirm it works on other boards in the past (admittedly at least one of those was before I added the `Serial.begin(9600);` line, but I wouldn't have thought that would make a difference).

Unfortunately since I'm not able to replicate the problem all I can offer to do is ask other people to have a go at running it to see if anyone else runs into the same problem.
I don't know anyone who uses Arch Linux though (or at least I'm not aware of anyone who does) and I don't have a spare computer to try to get Arch running myself, so if you know anyone who has a computer with a different OS who doesn't mind letting you test with that then that might be an easier option.

---

One of the reasons I find this quite odd is that despite appearances the library isn't actually doing anything particularly special internally - all the specialness is in the use of language features.
Behind the template magic it's all just garden variety integer arithmetic - integer add, subtract, multiply and divide with a bit of shifting and masking here and there and some conditional logic for the slightly more complicated functions.
There isn't even any looping or recursion and the serial stuff in the example is just regular string and float printing.

**Comment by barafael** [comment] 2018-03-10 18:55
I dusted off my good old windows installation and installed arduino from scratch there. The same thing happens, it reliably stops printing after

`Displaying b - a as float:
3.75

Displayin`

Tested with an Uno and a Mega 2560, both compiled and flashed with arch, now running on windows.

**Comment by Pharap** [comment] 2018-03-10 19:16
When you say "The same thing happens, it reliably stops printing after" is that with the version compiled and flashed with Arch or did you compile and flash on Windows?

**Comment by barafael** [comment] 2018-03-10 19:22
As I said, both compiled and flashed with arch, now running on windows.
I have since compiled the program anew, both with the lib from github and from the arduino library manager, on windows, and it works fine now.
* Frantically reboots into arch, fearing embarassment *

**Comment by barafael** [comment] 2018-03-10 19:33
Now back on arch: I tried just installing the library from the Arduino IDE lib manager - that worked on windows, but here I had to add a `Serial.begin(9600)` after which EVERYTHING WORKED (before, the sketch presumably hung on `while(!Serial)`).

I am going to try to now do the same with the library from github using platformio.

**Comment by barafael** [comment] 2018-03-10 19:48
Whenever I compile using platformio, it does not work. This could be because I need a `main.cpp` with a `main` function for platformio, so I did this modification instead of setup and loop:

`
int main() {
	Serial.begin(9600);
	while(!Serial);

	TestUQ8x8();
	TestSQ7x8();
    while(true) {}
}
`
which should be identical in my book. There could be an issue here, or during compilation with platformio, I don't know, but at this point it really seems much more certain that your library is just fine and not the problem here.

**Comment by Pharap** [comment] 2018-03-11 05:49
> I have since compiled the program anew, both with the lib from github and from the arduino library manager, on windows, and it works fine now.

I had a feeling it would be something related to Arch that was the problem since after ruling out the cable and the board that was the most different aspect.

> I had to add a `Serial.begin(9600)`

You must be using an out of date version, I already added that in `v1.0.5` (currently the latest release)
It was PR #15, I added it just under 2 months ago in response to [this comment](https://github.com/Pharap/FixedPointsArduino/issues/13#issuecomment-360261197).

> This could be because I need a main.cpp with a main function for platformio

I don't actually use PlatformIO myself, I added PlatformIO support on request of a person from the Arduboy forums (mentioned in the `v1.0.2` release).

According to [the PlatformIO docs](http://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually) having a `setup` and `loop` should work fine if you include `Arduino.h`, which makes sense since one of the Arduino files actually declares `main` (as a weak symbol so users can provide their own).

> which should be identical in my book

It's not completely identical, you'd also need to call `init` and `serialEventRun` (see [Arduino's `main.cpp`](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/main.cpp#L33)).
`loop` would certainly be optimised out, `initVariant` would be optimised out if there's nothing overriding it since it's declared empty and a weak symbol, and some board don't support `serialEventRun` (I think Leonardo is one of them) but other boards do so that may or may not be needed.

> There could be an issue here, or during compilation with PlatformIO, I don't know, but at this point it really seems much more certain that your library is just fine and not the problem here.

If it worked on Windows with the regular IDE then it seems the problem is either Arch or PlatformIO related.
Did adding the `Serial.begin(9600);` line get the example to work when uploading on Arch via the Arduino IDE?
If so we can rule out Arch as being a problem and assume it was the missing `Serial.begin` call.

As for PlatformIO, Getting the example to run for plaftormio should just be a matter of adding `#include <Arduino.h>`.
The test functions shouldn't need predeclaring.

If simply adding `#include <Arduino.h>` and renaming to `FixedPointCalculations.cpp` (assuming you're using the latest version with the `Serial.begin(9600);` line added) makes the example work then I might provide an extra PlatformIO specific example to make it easier for PlatformIO users, or put the current example in a state where it only has to be renamed to work on PlatformIO and maybe leave a comment at the top to remind people.

**Comment by barafael** [comment] 2018-03-16 12:40
> You must be using an out of date version, I already added that in v1.0.5 (currently the latest release)

1.0.5 is now available via Arduino IDE lib manager, I think 1.0.4 was latest when I installed last time but that could be my mistake.

> Did adding the Serial.begin(9600); line get the example to work when uploading on Arch via the Arduino IDE?
Nope.

> As for PlatformIO, Getting the example to run for plaftormio should just be a matter of adding #include <Arduino.h>.

No sauce!

> It's not completely identical, you'd also need to call init and serialEventRun (see Arduino's main.cpp).
Ok, so I tried calling the functions that real arduino main calls, but then there is a duplicate definition of main, of course. So when I use just setup() and loop(), it works fine with platformio. Otherwise, using main, I could not get it to run ok. I don't have a problem with calling setup() and loop(), I just wonder why it always seemed to work ok (there where several issues with serial output, none so severe as this one though). And I think most platformio users use setup and loop anyway.

Thank you for your patience for this somewhat silly issue!

**Closed** 2018-03-16 12:52 UTC

**Comment by Pharap** [comment] 2018-03-16 14:02
> Thank you for your patience for this somewhat silly issue!

No problem, as long as you got it all up and running in the end.
It's in everyone's interest for issues to be reported and solved.
I just hope it is an issue in the other code and not related to FixedPoints, otherwise I'm stumped.
It does seem to be that way at least.
